name: my_wellness
description: "Theo Dõi Sức Khỏe"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  animations: any
  firebase_core: ^3.13.1
  firebase_analytics: ^11.4.6
  firebase_auth: ^5.5.4
  google_fonts: any


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  direct_select: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
