name: my_wellness
description: "Theo Dõi Sức Khỏe"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  animations: any
  firebase_core: ^3.13.1
  firebase_analytics: ^11.4.6
  firebase_auth: ^5.5.4
  google_fonts: any
  cloud_firestore: any
  fl_chart: ^0.66.2
  intl: ^0.18.1
  provider: ^6.1.1
  shared_preferences: ^2.1.0
  image_picker: ^1.0.0
  flutter_staggered_animations: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  direct_select: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/walk.gif

